---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(tidytext)
library(ggwordcloud)
library(hcandersenr)
library(harrypotter)
library(janeaustenr)
library(wordcloud)
library(RColorBrewer)
library(text2vec)
```

# MVP 1

```{r}
little_mermaid <- hcandersen_en %>% 
  filter(book == "The little mermaid") %>% 
  unnest_tokens(word, text) %>%
  count(word) %>% 
  anti_join(stop_words) %>% 
  arrange(desc(n))

words <- little_mermaid$word
freq <- little_mermaid$n

wordcloud(
  words = words,
  freq = freq,
  max.words = 200,
  rot.per = 0.35,
  colors=brewer.pal(8, "Dark2")
)

ggwordcloud(
  words = little_mermaid$word,
  freq = little_mermaid$n,
  min.freq = 10
)
```

# MVP 2

```{r}
top_10_sentimental_words <- little_mermaid %>% 
  inner_join(get_sentiments("bing")) %>% 
  head(10) 

top_10_sentimental_words %>% 
  ggplot() +
  aes(x = reorder(word, n), y = n, fill = sentiment) +
  geom_col() +
  labs(
    x = "word",
    y = "count",
    fill = ""
  ) +
  theme_bw()
```

# MVP 3

```{r}
potter_df <- tibble(
    text = chamber_of_secrets,
    id = 1:length(chamber_of_secrets)
  )
  
potter_df %>%   
  unnest_tokens(bigram, text, token = "ngrams", n = 2) %>% 
  separate(bigram, c("word_1", "word_2"), sep = " ") %>% 
  filter(word_1 == "very") %>%
  inner_join(get_sentiments("bing"), by = c("word_2" = "word")) %>% 
  unite(bigram, word_1, word_2, sep = " ") %>% 
  count(bigram, sentiment, sort = TRUE)
```

# MVP 4

```{r}
titles <- c("philosophers stone", "chamber of secrets", "prisoner of azkaban", 
            "goblet of fire", "order of the phoenix", "half blood prince", "deathly hallows", "Pride and Prejudice", "Sense and Sensibility", "Emma", "Persuasion", "Mansfield Park", "Northanger Abbey")

books <- list(philosophers_stone, chamber_of_secrets, prisoner_of_azkaban, 
            goblet_of_fire, order_of_the_phoenix, half_blood_prince, deathly_hallows, 
            prideprejudice, sensesensibility, emma, persuasion, mansfieldpark, northangerabbey)

books <- map_chr(books, paste, collapse = " ")

all_books_df <- tibble(
  text = books,
  title = titles
) %>% 
  unnest_tokens(word, text) 

all_books_tf_idf <- all_books_df %>% 
  count(word, title) %>% 
  bind_tf_idf(word, title, n)

all_books_tf_idf %>% 
  group_by(title) %>% 
  slice_max(order_by = tf_idf, n = 1)
```

# MVP 5

```{r}
library(text2vec)
glimpse(movie_review)
```

# MVP 6

```{r}
little_mermaid <- hcandersen_en %>% 
  filter(book == "The little mermaid") %>%
  mutate(sentence = row_number()) %>% 
  unnest_tokens(word, text)

little_mermaid_df <- tibble(
  word = little_mermaid$word,
  sentence = little_mermaid$sentence
) %>% 
  anti_join(stop_words) %>% 
  inner_join(get_sentiments("afinn")) 

little_mermaid_df %>% 
  group_by(sentence) %>% 
  summarise(
    mean_sentiment = mean(value)
  ) %>% 
  ggplot() +
  aes(x = sentence, y = mean_sentiment) +
  geom_point() +
  geom_smooth(se = FALSE) +
  labs(
    y = "sentiment"
  ) +
  theme_bw()
```

```{r}
thumbelina <- hcandersen_en %>% 
  filter(book == "Thumbelina") %>%
  mutate(sentence = row_number()) %>% 
  unnest_tokens(word, text)

thumbelina_df <- tibble(
  word = thumbelina$word,
  sentence = thumbelina$sentence
) %>% 
  anti_join(stop_words) %>% 
  inner_join(get_sentiments("afinn")) 

thumbelina_df %>% 
  group_by(sentence) %>% 
  summarise(
    mean_sentiment = mean(value)
  ) %>% 
  ggplot() +
  aes(x = sentence, y = mean_sentiment) +
  geom_point() +
  geom_smooth(se = FALSE) +
  labs(
    y = "sentiment"
  ) +
  theme_bw()
```

```{r}
library(text2vec)
glimpse(movie_review)
```

