---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(infer)
```

# Qu. 1 

```{r}
mammal_data <- ggplot2::msleep

summary(mammal_data)
```

# Qu. 2 

```{r}
# we are comparing the sample mean to a known value therefore a one sample test

H0 != 7 ??????????
Ha = 7

# significance level, alpha = 0.05

# calculate the mean sleep_total of our sample
observed_stat <- mammal_data %>% 
  summarise(mean_sleep = mean(sleep_total))
observed_stat

# create the null distribution of our sample
null_distribution <- mammal_data %>% 
  specify(response = sleep_total) %>% 
  hypothesise(null = "point", mu = 7) %>% 
  generate(reps = 15000, type = "bootstrap") %>% 
  calculate(stat = "mean")

null_distribution %>% 
  visualise(bins = 30) +
  shade_p_value(obs_stat = observed_stat, direction = "both")

null_distribution %>% 
  get_p_value(obs_stat = observed_stat, direction = "both")

# since p is less than alpha we can reject the null hypothesis - the mean sleep_total
# of out sample differs from that of jabberwockies
```

# Qu. 3

```{r}
# we are comparing averages of two different samples; omnivores and carnivores therefore this is a two sided test

# H0 : uomni - uherbi = 0
# H1 : uomni - uherbi != 0

# significance level, alpha = 0.05

# create the null distribution
null_distribution <- mammal_data %>%
  filter(vore %in% c("omni", "herbi")) %>% 
  specify(response = sleep_total, explanatory = vore) %>% 
  hypothesise(null = "independence") %>% 
  generate(reps = 1000, type = "permute") %>% 
  calculate(stat = "diff in means", order = c("omni", "herbi"))
null_distribution

# calculate the observed stat
observed_stat <- mammal_data %>% 
  filter(vore %in% c("omni", "herbi")) %>% 
  specify(sleep_total ~ vore) %>% 
  calculate(stat = "diff in means", order = c("omni", "herbi"))
observed_stat

# plot null_distribution
null_distribution %>% 
  visualise(bins = 30) +
  shade_p_value(obs_stat = observed_stat, direction = "both")

# find the p value
null_distribution %>% 
  get_p_value(obs_stat = observed_stat, direction = "both")

# p value is less that 0.05 so we can reject the null hypothesis
```

# Qu. 4

```{r}
# one sample test for proportion

# H0 : πdom < 5
# Ha : πdom > 5

# create is_domesticated variable & remove NAs
mammal_data_dom <- mammal_data %>% 
  mutate(is_domesticated = ifelse(conservation == "domesticated", 
                                  "domesticated", "not domesticated")
  ) %>% 
  filter(!is.na(conservation))

# calculate observed stat
observed_stat <- mammal_data_dom %>% 
  specify(response = is_domesticated, success = "domesticated") %>% 
  calculate(stat = "prop")
observed_stat

# create null distribution
null_distribution <- mammal_data_dom %>% 
  specify(response = is_domesticated, success = "domesticated") %>% 
  hypothesise(null = "point", p = 0.05) %>% 
  generate(reps = 10000, type = "draw") %>% 
  calculate(stat = "prop")


# plot null distribution
null_distribution %>% 
  visualise(bins = 30) +
  shade_p_value(obs_stat = observed_stat, direction = "right")

# get p value
p_value <- null_distribution %>% 
  get_p_value(obs_stat = observed_stat, direction = "right")
p_value

# as p is less than alpha the null hypothesis can be rejected
```

# Qu. 1.2



# Section 1.2

Qu2 1 - Fail to reject the null hypothesis
Qu. 2 - Reject the null hypothesis
Qu. 3 - Fail to reject the null hypothesis

