---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janeaustenr)
library(tidytext)
library(textdata)
```

```{r}
titles <- c("prideprejudice", "sensesensibility")

books <- list(prideprejudice, sensesensibility)

books <- purrr::map_chr(books, paste, collapse = " ") 
str(books)
```

```{r}
all_books_df <- tibble(
  title = titles,
  text = books
) %>%
  unnest_tokens(word, text)

head(all_books_df)
```

```{r}
# Find the most common words in both Pride & Prejudice and Sense & Sensibility.
all_books_df %>% 
  count(word, sort = TRUE) %>% 
  slice_max(1)
```

```{r}
all_books_df %>% 
  anti_join(stop_words) %>% 
  count(word, sort = TRUE) %>% 
  slice_max(n, n = 5)
```

```{r}
all_books_df %>% 
  inner_join(get_sentiments("bing")) %>% 
  count(word, sort = TRUE) %>% 
  slice_max(n, n = 5)
```

```{r}
book_pride <- tibble(
    text = prideprejudice,
    sentence = 1:length(prideprejudice)
  ) %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words)

pride_sentiment <- book_pride %>% 
  inner_join(get_sentiments("afinn")) 

pride_sentiment %>% 
  group_by(sentence) %>% 
  summarise(
    mean_sentiment = mean(value)
  ) %>% 
  ggplot() +
  aes(x = sentence, y = mean_sentiment) +
  geom_point(alpha = 0.1) +
  geom_smooth() +
  theme_bw()
```

```{r}
book_sensi <- tibble(
    text = sensesensibility,
    sentence = 1:length(sensesensibility)
  ) %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words)

sensi_sentiment <- book_sensi %>% 
  inner_join(get_sentiments("afinn")) 

sensi_sentiment %>% 
  group_by(sentence) %>% 
  summarise(
    mean_sentiment = mean(value)
  ) %>% 
  ggplot() +
  aes(x = sentence, y = mean_sentiment) +
  geom_point(alpha = 0.1) +
  geom_smooth() +
  theme_bw()
```
